In [2]:
import numpy as np

#Random number Seed\
#ndarray - 

In [5]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [10]:
#Inclusive start & stop exclusive 
np.arange(start=1, stop=6, step=2)

array([1, 3, 5])

In [9]:
#Random number (low - inclusvie & hight exclusvie)
np.random.randint(low=0, high=10, size=(3,4))

array([[6, 9, 4, 0],
       [6, 5, 5, 3],
       [1, 6, 3, 5]])

In [17]:
a = np.arange(1,4)
b = np.arange(4,7)
c = np.arange(8,11)
d = np.column_stack((a,b))

In [18]:
d.shape

(3, 2)

In [20]:
x = np.arange(6)
b = x.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [21]:
b.T

array([[0, 2, 4],
       [1, 3, 5]])

In [22]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [24]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [25]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])